# Generated by Django 4.0.2 on 2023-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0002_casting_call_alter_user_registration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, upload_to='images/contest/audio')),
            ],
        ),
        migrations.AddField(
            model_name='casting_call',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/casting/banner'),
        ),
    ]
