# Generated by Django 4.0.2 on 2023-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastoonnApp', '0004_contest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='posting_date',
            field=models.DateField(null=True),
        ),
    ]
